#pragma once

namespace MiniFazenda::Compartilhado::Constantes {

constexpr int TAMANHO_INICIAL_GRID = 12;
constexpr int TAMANHO_MAXIMO_GRID = 24;
constexpr int INCREMENTO_TAMANHO_GRID = 2;

constexpr int QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL_ALOCADA = 256;
constexpr int QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL_ALOCADA = 256;
constexpr int QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL = QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL_ALOCADA;
constexpr int QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL = QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL_ALOCADA;
constexpr int TOTAL_DE_TILES_DA_GRADE_GLOBAL =
    QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL_ALOCADA * QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL_ALOCADA;

constexpr int QUANTIDADE_DE_COLUNAS_DO_NUCLEO_INICIAL = 2;
constexpr int QUANTIDADE_DE_LINHAS_DO_NUCLEO_INICIAL = 2;

constexpr int COLUNA_CENTRAL_DA_GRADE_GLOBAL = QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL / 2;
constexpr int LINHA_CENTRAL_DA_GRADE_GLOBAL = QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL / 2;

constexpr int COLUNA_INICIAL_DO_NUCLEO_INICIAL =
    COLUNA_CENTRAL_DA_GRADE_GLOBAL - (QUANTIDADE_DE_COLUNAS_DO_NUCLEO_INICIAL / 2);
constexpr int LINHA_INICIAL_DO_NUCLEO_INICIAL =
    LINHA_CENTRAL_DA_GRADE_GLOBAL - (QUANTIDADE_DE_LINHAS_DO_NUCLEO_INICIAL / 2);

constexpr int UNIDADES_DE_OCUPACAO_POR_CANTEIRO = 2;
constexpr int LARGURA_DA_UNIDADE_DE_OCUPACAO = 64;
constexpr int ALTURA_DA_UNIDADE_DE_OCUPACAO = 32;
constexpr int QUANTIDADE_DE_COLUNAS_DA_GRADE_DE_OCUPACAO_GLOBAL =
    QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL * UNIDADES_DE_OCUPACAO_POR_CANTEIRO;
constexpr int QUANTIDADE_DE_LINHAS_DA_GRADE_DE_OCUPACAO_GLOBAL =
    QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL * UNIDADES_DE_OCUPACAO_POR_CANTEIRO;

constexpr float VELOCIDADE_PERSONAGEM_EM_CELULAS_POR_SEGUNDO = 5.0f;
constexpr float TOLERANCIA_CHEGADA_PERSONAGEM_EM_CELULAS = 0.001f;
constexpr float VELOCIDADE_PERSONAGEM_EM_UNIDADES_DE_OCUPACAO_POR_SEGUNDO =
    VELOCIDADE_PERSONAGEM_EM_CELULAS_POR_SEGUNDO * UNIDADES_DE_OCUPACAO_POR_CANTEIRO;
constexpr float TOLERANCIA_CHEGADA_PERSONAGEM_EM_UNIDADES_DE_OCUPACAO =
    TOLERANCIA_CHEGADA_PERSONAGEM_EM_CELULAS * UNIDADES_DE_OCUPACAO_POR_CANTEIRO;

} // namespace MiniFazenda::Compartilhado::Constantes
