#pragma once

namespace MiniFazenda::Compartilhado::Constantes {

constexpr int LARGURA_DA_JANELA = 1280;
constexpr int ALTURA_DA_JANELA = 720;

constexpr int CENTRO_VISUAL_BACKGROUND_X = 576;
constexpr int CENTRO_VISUAL_BACKGROUND_Y = 296;

constexpr int TAXA_DE_QUADROS_DESEJADA = 60;
constexpr int MILISSEGUNDOS_POR_QUADRO = 1000 / TAXA_DE_QUADROS_DESEJADA;

constexpr int TAMANHO_INICIAL_GRID = 12;
constexpr int TAMANHO_MAXIMO_GRID = 24;
constexpr int INCREMENTO_TAMANHO_GRID = 2;

constexpr int QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL_ALOCADA = 256;
constexpr int QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL_ALOCADA = 256;
constexpr int QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL = QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL_ALOCADA;
constexpr int QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL = QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL_ALOCADA;
constexpr int TOTAL_DE_TILES_DA_GRADE_GLOBAL =
    QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL_ALOCADA * QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL_ALOCADA;

constexpr int QUANTIDADE_DE_COLUNAS_DO_NUCLEO_INICIAL = 2;
constexpr int QUANTIDADE_DE_LINHAS_DO_NUCLEO_INICIAL = 2;

constexpr int COLUNA_CENTRAL_DA_GRADE_GLOBAL = QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL / 2;
constexpr int LINHA_CENTRAL_DA_GRADE_GLOBAL = QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL / 2;

constexpr int COLUNA_INICIAL_DO_NUCLEO_INICIAL =
    COLUNA_CENTRAL_DA_GRADE_GLOBAL - (QUANTIDADE_DE_COLUNAS_DO_NUCLEO_INICIAL / 2);
constexpr int LINHA_INICIAL_DO_NUCLEO_INICIAL =
    LINHA_CENTRAL_DA_GRADE_GLOBAL - (QUANTIDADE_DE_LINHAS_DO_NUCLEO_INICIAL / 2);

constexpr int COLUNA_DE_ORIGEM_VISUAL_DA_GRADE_GLOBAL = COLUNA_INICIAL_DO_NUCLEO_INICIAL;
constexpr int LINHA_DE_ORIGEM_VISUAL_DA_GRADE_GLOBAL = LINHA_INICIAL_DO_NUCLEO_INICIAL;

constexpr int LARGURA_DO_CANTEIRO = 128;
constexpr int ALTURA_DO_CANTEIRO = 64;

constexpr float ZOOM_INICIAL = 1.0f;
constexpr float ZOOM_MINIMO = 0.5f;
constexpr float ZOOM_MAXIMO = 2.0f;
constexpr float PASSO_DO_ZOOM = 0.1f;
constexpr float DESACELERACAO_DO_PAN = 1600.0f;
constexpr float FRACAO_MINIMA_VISIVEL_AO_PAN = 0.25f;

constexpr float VELOCIDADE_PERSONAGEM_EM_CELULAS_POR_SEGUNDO = 5.0f;
constexpr float TOLERANCIA_CHEGADA_PERSONAGEM_EM_CELULAS = 0.001f;

constexpr int TAMANHO_DO_BOTAO_DA_INTERFACE = 52;
constexpr int ESPACAMENTO_DOS_BOTOES = 12;

constexpr const char* TITULO_DA_JANELA = "Jardim Tropical v1.0.0";

} // namespace MiniFazenda::Compartilhado::Constantes
