#pragma once

namespace Constantes {

constexpr int LARGURA_DA_JANELA = 1280;
constexpr int ALTURA_DA_JANELA = 720;
constexpr int TAXA_DE_QUADROS_DESEJADA = 60;
constexpr int MILISSEGUNDOS_POR_QUADRO = 1000 / TAXA_DE_QUADROS_DESEJADA;

constexpr int TAMANHO_INICIAL_GRID = 12;
constexpr int TAMANHO_MAXIMO_GRID = 24;

// Tamanho do buffer interno usado para armazenar a grade global alocada.
// O grid visível jogável usa tamanhos crescentes em blocos de +2 até o máximo definido.
constexpr int QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL_ALOCADA = 256;
constexpr int QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL_ALOCADA = 256;
constexpr int TOTAL_DE_TILES_DA_GRADE_GLOBAL =
    QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL_ALOCADA * QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL_ALOCADA;

constexpr int QUANTIDADE_DE_COLUNAS_DO_NUCLEO_INICIAL = 2;
constexpr int QUANTIDADE_DE_LINHAS_DO_NUCLEO_INICIAL = 2;

constexpr int COLUNA_CENTRAL_DA_GRADE_GLOBAL = QUANTIDADE_DE_COLUNAS_DA_GRADE_GLOBAL_ALOCADA / 2;
constexpr int LINHA_CENTRAL_DA_GRADE_GLOBAL = QUANTIDADE_DE_LINHAS_DA_GRADE_GLOBAL_ALOCADA / 2;

constexpr int COLUNA_INICIAL_DO_NUCLEO_INICIAL =
    COLUNA_CENTRAL_DA_GRADE_GLOBAL - (QUANTIDADE_DE_COLUNAS_DO_NUCLEO_INICIAL / 2);
constexpr int LINHA_INICIAL_DO_NUCLEO_INICIAL =
    LINHA_CENTRAL_DA_GRADE_GLOBAL - (QUANTIDADE_DE_LINHAS_DO_NUCLEO_INICIAL / 2);

constexpr int COLUNA_DE_ORIGEM_VISUAL_DA_GRADE_GLOBAL = COLUNA_INICIAL_DO_NUCLEO_INICIAL;
constexpr int LINHA_DE_ORIGEM_VISUAL_DA_GRADE_GLOBAL = LINHA_INICIAL_DO_NUCLEO_INICIAL;

constexpr int LARGURA_DO_CANTEIRO = 128;
constexpr int ALTURA_DO_CANTEIRO = 64;

constexpr int TEMPO_PARA_CRESCER = 6;
constexpr int TEMPO_PARA_MADURAR = 14;
constexpr int TEMPO_PARA_MORRER = 34;

constexpr int TAMANHO_DO_BOTAO_DA_INTERFACE = 52;
constexpr int ESPACAMENTO_DOS_BOTOES = 12;

constexpr const char* TITULO_DA_JANELA = "MiniFazenda2 v1.0.0";

} // namespace Constantes
